export const GET_NUM_OF_ITEM='GET_NUM_OF_ITEM';
export const UPDATE_NUM_OF_ITEM='UPDATE_NUM_OF_ITEM';

export const SET_PRODUCTS='SET_PRODUCTS';
export const SET_SUMMARY='SET_SUMMARY';
export const CLEAR_PRODUCTS='CLEAR_PRODUCTS';
export const SUBMIT_SEARCH_VALUE='SUBMIT_SEARCH_VALUE';
